<?php

namespace Database\Seeders;

use App\Models\Enums\Skill;
use App\Models\Game;
use App\Models\Enums\G;
use App\Models\Player;
use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Artisan;

class DatabaseSeeder extends Seeder
{
    use WithoutModelEvents;

    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        Game::insert(array_map(fn (G $game) => [
            'id' => $game->value,
            'name' => $game->label(),
            'room' => $game->room(),
            'optimal_players' => $game->optimalPlayers(),
        ], G::cases()));

        Artisan::call('app:update-game-info');
        Artisan::call('app:update-player-data');
        Artisan::call('app:update-league-data');

        $skills = [
            'Frosttea' => [
                G::Grid->value => Skill::Great,
                G::FlashMines->value => Skill::Neutral,
                G::Strategy->value => Skill::Neutral,
                G::Zones->value => Skill::Great,
                G::SimonSays->value => Skill::Neutral,
                G::Trivial->value => Skill::Neutral,
                G::Barrage->value => Skill::Great,
                G::FifteenGreen->value => Skill::Good,
                G::Words->value => Skill::Good,
                G::Numbers->value => Skill::Neutral,
                G::Relay->value => Skill::Great,
                G::Sequence->value => Skill::Good,
                G::Spellinator->value => Skill::Neutral,
                G::Bop->value => Skill::Great,
                G::Labyrinth->value => Skill::Good,
                G::MegaGrid->value => Skill::Great,
                G::Jigsaw->value => Skill::Unknown,
                G::OrderUp->value => Skill::Unknown,
                G::MegaZones->value => Skill::Great,
                G::Statues->value => Skill::Neutral,
                G::MegaRelay->value => Skill::Great,
                G::Maze->value => Skill::Great,
                G::Gauntlet->value => Skill::Great,
                G::Zap->value => Skill::Unknown,
                G::Defuse->value => Skill::Unknown,
                G::LaserRelay->value => Skill::Great,
                G::Flip->value => Skill::Unknown,
                G::Dartmouth->value => Skill::Great,
                G::Asteroids->value => Skill::Great,
                G::Terminal->value => Skill::Unknown,
                G::Seeker->value => Skill::Great,
                G::Gems->value => Skill::Great,
                G::Link->value => Skill::Great,
                G::Mines->value => Skill::Unknown,
                G::Undercover->value => Skill::Neutral,
                G::BulletTrain->value => Skill::Good,
                G::Supermarket->value => Skill::Neutral,
                G::InsideOut->value => Skill::Unknown,
                G::Spot->value => Skill::Great,
                G::Wormholes->value => Skill::Neutral,
                G::Jumble->value => Skill::Unknown,
                G::Oddball->value => Skill::Unknown,
                G::Stopwatch->value => Skill::Unknown,
            ],
            'Whumps' => [
                G::Grid->value => Skill::Great,
                G::FlashMines->value => Skill::Poor,
                G::Strategy->value => Skill::Low,
                G::Zones->value => Skill::Great,
                G::SimonSays->value => Skill::Neutral,
                G::Trivial->value => Skill::Great,
                G::Barrage->value => Skill::Neutral,
                G::FifteenGreen->value => Skill::Good,
                G::Words->value => Skill::Neutral,
                G::Numbers->value => Skill::Good,
                G::Relay->value => Skill::Great,
                G::Sequence->value => Skill::Great,
                G::Spellinator->value => Skill::Neutral,
                G::Bop->value => Skill::Great,
                G::Labyrinth->value => Skill::Neutral,
                G::MegaGrid->value => Skill::Great,
                G::Jigsaw->value => Skill::Good,
                G::OrderUp->value => Skill::Good,
                G::MegaZones->value => Skill::Great,
                G::Statues->value => Skill::Good,
                G::MegaRelay->value => Skill::Great,
                G::Maze->value => Skill::Good,
                G::Gauntlet->value => Skill::Great,
                G::Zap->value => Skill::Neutral,
                G::Defuse->value => Skill::Neutral,
                G::LaserRelay->value => Skill::Good,
                G::Flip->value => Skill::Neutral,
                G::Dartmouth->value => Skill::Neutral,
                G::Asteroids->value => Skill::Neutral,
                G::Terminal->value => Skill::Neutral,
                G::Seeker->value => Skill::Neutral,
                G::Gems->value => Skill::Neutral,
                G::Link->value => Skill::Neutral,
                G::Mines->value => Skill::Unknown,
                G::Undercover->value => Skill::Great,
                G::BulletTrain->value => Skill::Good,
                G::Supermarket->value => Skill::Good,
                G::InsideOut->value => Skill::Poor,
                G::Spot->value => Skill::Great,
                G::Wormholes->value => Skill::Good,
                G::Jumble->value => Skill::Good,
                G::Oddball->value => Skill::Good,
                G::Stopwatch->value => Skill::Good,
            ],
            'Rainbow_Spice' => [
                G::Grid->value => Skill::Good,
                G::FlashMines->value => Skill::Neutral,
                G::Strategy->value => Skill::Neutral,
                G::Zones->value => Skill::Good,
                G::SimonSays->value => Skill::Low,
                G::Trivial->value => Skill::Low,
                G::Barrage->value => Skill::Poor,
                G::FifteenGreen->value => Skill::Poor,
                G::Words->value => Skill::Neutral,
                G::Numbers->value => Skill::Low,
                G::Relay->value => Skill::Good,
                G::Sequence->value => Skill::Neutral,
                G::Spellinator->value => Skill::Neutral,
                G::Bop->value => Skill::Good,
                G::Labyrinth->value => Skill::Neutral,
                G::MegaGrid->value => Skill::Good,
                G::Jigsaw->value => Skill::Low,
                G::OrderUp->value => Skill::Low,
                G::MegaZones->value => Skill::Good,
                G::Statues->value => Skill::Good,
                G::MegaRelay->value => Skill::Good,
                G::Maze->value => Skill::Good,
                G::Gauntlet->value => Skill::Good,
                G::Zap->value => Skill::Neutral,
                G::Defuse->value => Skill::Neutral,
                G::LaserRelay->value => Skill::Good,
                G::Flip->value => Skill::Low,
                G::Dartmouth->value => Skill::Low,
                G::Asteroids->value => Skill::Low,
                G::Terminal->value => Skill::Low,
                G::Seeker->value => Skill::Low,
                G::Gems->value => Skill::Neutral,
                G::Link->value => Skill::Neutral,
                G::Mines->value => Skill::Unknown,
                G::Undercover->value => Skill::Low,
                G::BulletTrain->value => Skill::Good,
                G::Supermarket->value => Skill::Good,
                G::InsideOut->value => Skill::Low,
                G::Spot->value => Skill::Good,
                G::Wormholes->value => Skill::Good,
                G::Jumble->value => Skill::Low,
                G::Oddball->value => Skill::Unknown,
                G::Stopwatch->value => Skill::Neutral,
            ],
            'Jtep' => [
                G::Grid->value => Skill::Good,
                G::FlashMines->value => Skill::Unknown,
                G::Strategy->value => Skill::Great,
                G::Zones->value => Skill::Neutral,
                G::SimonSays->value => Skill::Great,
                G::Trivial->value => Skill::Unknown,
                G::Barrage->value => Skill::Great,
                G::FifteenGreen->value => Skill::Good,
                G::Words->value => Skill::Unknown,
                G::Numbers->value => Skill::Great,
                G::Relay->value => Skill::Good,
                G::Sequence->value => Skill::Unknown,
                G::Spellinator->value => Skill::Neutral,
                G::Bop->value => Skill::Poor,
                G::Labyrinth->value => Skill::Low,
                G::MegaGrid->value => Skill::Low,
                G::Jigsaw->value => Skill::Poor,
                G::OrderUp->value => Skill::Neutral,
                G::MegaZones->value => Skill::Good,
                G::Statues->value => Skill::Low,
                G::MegaRelay->value => Skill::Good,
                G::Maze->value => Skill::Poor,
                G::Gauntlet->value => Skill::Unknown,
                G::Zap->value => Skill::Good,
                G::Defuse->value => Skill::Unknown,
                G::LaserRelay->value => Skill::Poor,
                G::Flip->value => Skill::Unknown,
                G::Dartmouth->value => Skill::Great,
                G::Asteroids->value => Skill::Neutral,
                G::Terminal->value => Skill::Great,
                G::Seeker->value => Skill::Unknown,
                G::Gems->value => Skill::Neutral,
                G::Link->value => Skill::Low,
                G::Mines->value => Skill::Unknown,
                G::Undercover->value => Skill::Unknown,
                G::BulletTrain->value => Skill::Neutral,
                G::Supermarket->value => Skill::Great,
                G::InsideOut->value => Skill::Unknown,
                G::Spot->value => Skill::Low,
                G::Wormholes->value => Skill::Neutral,
                G::Jumble->value => Skill::Neutral,
                G::Oddball->value => Skill::Unknown,
                G::Stopwatch->value => Skill::Unknown,
            ],
            'Twongx' => [
                G::Grid->value => Skill::Neutral,
                G::FlashMines->value => Skill::Unknown,
                G::Strategy->value => Skill::Neutral,
                G::Zones->value => Skill::Neutral,
                G::SimonSays->value => Skill::Neutral,
                G::Trivial->value => Skill::Neutral,
                G::Barrage->value => Skill::Good,
                G::FifteenGreen->value => Skill::Good,
                G::Words->value => Skill::Great,
                G::Numbers->value => Skill::Great,
                G::Relay->value => Skill::Good,
                G::Sequence->value => Skill::Good,
                G::Spellinator->value => Skill::Unknown,
                G::Bop->value => Skill::Low,
                G::Labyrinth->value => Skill::Low,
                G::MegaGrid->value => Skill::Neutral,
                G::Jigsaw->value => Skill::Unknown,
                G::OrderUp->value => Skill::Good,
                G::MegaZones->value => Skill::Neutral,
                G::Statues->value => Skill::Neutral,
                G::MegaRelay->value => Skill::Neutral,
                G::Maze->value => Skill::Unknown,
                G::Gauntlet->value => Skill::Unknown,
                G::Zap->value => Skill::Great,
                G::Defuse->value => Skill::Great,
                G::LaserRelay->value => Skill::Great,
                G::Flip->value => Skill::Neutral,
                G::Dartmouth->value => Skill::Neutral,
                G::Asteroids->value => Skill::Poor,
                G::Terminal->value => Skill::Neutral,
                G::Seeker->value => Skill::Neutral,
                G::Gems->value => Skill::Great,
                G::Link->value => Skill::Unknown,
                G::Mines->value => Skill::Unknown,
                G::Undercover->value => Skill::Unknown,
                G::BulletTrain->value => Skill::Neutral,
                G::Supermarket->value => Skill::Good,
                G::InsideOut->value => Skill::Neutral,
                G::Spot->value => Skill::Great,
                G::Wormholes->value => Skill::Unknown,
                G::Jumble->value => Skill::Unknown,
                G::Oddball->value => Skill::Unknown,
                G::Stopwatch->value => Skill::Unknown,
            ],
        ];

        foreach ($skills as $playerName => $gameSkills) {
            $player = Player::where('name', $playerName)->first();
            foreach ($gameSkills as $gameId => $skill) {
                $player->games()
                    ->updateExistingPivot($gameId, ['skill' => $skill->value]);
            }
        }
    }
}
